# Generated by Django 4.2.1 on 2023-07-17 12:52

from django.db import migrations
from django.conf import settings

def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')
    domain = 'ibed-cvat.science.uva.nl'
    name = 'IBED-CVAT'
	
    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': name}
    )

class Migration(migrations.Migration):

    dependencies = [
	('sites', '0002_alter_domain_unique'),
        ('engine', '0073_alter_attributespec_default_value_and_more'),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]

