services:
  nuclio:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.8.14-amd64
    restart: always
    networks:
      - cvat
    volumes:
      - /tmp:/tmp
      - /data/podman.sock:/var/run/docker.sock:ro
    environment:
      http_proxy:
      https_proxy:
      no_proxy: 172.28.0.1,${no_proxy:-}
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
      NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
    ports:
      - '8070:8070'
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"

  cvat_server:
    environment:
      CVAT_SERVERLESS: 1
    extra_hosts:
      - "host.containers.internal:127.0.0.1"

  cvat_worker_annotation:
    extra_hosts:
      - "host.containers.internal:127.0.0.1"
