# Generated by Django 4.2.1 on 2023-07-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='GB_limit',
            field=models.IntegerField(default=0),
        ),
    ]